### ISSUE TITLE
Centre?

### ISSUE THREAD

**Issue by przemekkowal** [imRohan/ubersicht-morning.widget#2]
Hi,

How do I centre the clock on both build in and extended monitor? Currently it's sitting somewhere up to the left top corner.

**Comment by imRohan** [comment]
You'd probably get the best result if you played around with the `container` class styles.

In morning.coffee, check out lines 17 & 23, where it says `margin-top` and `margin-left`. These two attributes position the clock on the screen.

Play around with those, and the clock will move around the screen. Also, since you have dual monitors, there could be something funny going on with how the monitors are rendered. If the second monitor is "extended" the two screens will act like one, very large screen!

**Comment by przemekkowal** [comment]
Well, I got my build in MacBook Pro screen and one that's external. It's weird if I cannot centre the screen by default without playing with code. Well, I can move clock to the centre on screen one, however the screen two clock is in the right lower corner. If I unplug external monitor it's somewhere in weird place. How do I make it always on the centre on both internal and external monitor?

**Comment by imRohan** [comment]
I think this issue has more to do with display configs rather than the widget, so lets figure this out. Email me and i'll help you as best as i can.

Closing this issue for the time being.
